//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTiempos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlDeTiempos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anadir {
            get {
                object obj = ResourceManager.GetObject("anadir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015
        ///2016
        ///2017
        ///2018
        ///2019
        ///2020
        ///2021
        ///2022.
        /// </summary>
        internal static string año {
            get {
                return ResourceManager.GetString("año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria
        ///Contabilidad
        ///Administracion
        ///Trabajo especial
        ///Otros
        ///
        ///.
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bloquear {
            get {
                object obj = ResourceManager.GetObject("bloquear", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buscar {
            get {
                object obj = ResourceManager.GetObject("buscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cerrar {
            get {
                object obj = ResourceManager.GetObject("cerrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Planeacion Estrategica
        ///2. EFECTIVO E INVERSIONES TEMPORALES
        ///3. INMUEBLES, MAQUINARIA Y EQUIPO
        ///4. INVENTARIOS
        ///5. Planeación de Auditoría Detallada
        ///6. Determinacion de la Materialidad
        ///7. Análisis de Variaciones en estados financieros 
        ///8. INVERSIONES TEMPORALES
        ///9. Revision de cifras dictaminadas
        ///10. CUENTAS POR COBRAR 
        ///10. VENTAS
        ///11. OTROS ACTIVOS
        ///12. CUENTAS POR PAGAR- PROVEEDORES
        ///12. CUENTAS POR PAGAR- DOCUMENTOS
        ///12. CUENTAS POR PAGAR- ANTICIPOS DE CLIENTES
        ///13. CIAS. AFILIADAS Y RELACIONADA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string concepto {
            get {
                return ResourceManager.GetString("concepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap documento {
            get {
                object obj = ResourceManager.GetObject("documento", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIANZAS AFECTUOSAS, S.A de C.V
        ///ADMINISTRADORA DE OBRAS Y CONCESIONES, S.A de C.V
        ///ASCENCIO SOULES Y CIA, S.C
        ///CONSTRUCTORA MAKRO, S.A de C.V
        ///CORPORATIVO INTEGRAL DE VIVIENDA, S.A. de C.V.
        ///DISTRIBUIDORA PIPILA, S. de R.L. de C.V.
        ///HOGAR PARA NINIOS NECESITADOS CRISTO POR SU MUNDO, A.C.
        ///MADERAS Y MATERIALES, JR, S.A. de C.V.
        ///MAGNAMAQ, S.A. de C.V.
        ///OPERADORA FARMACEUTICA DE BAJA CALIFORNIA, S. de R.L. de C.V.
        ///PIEDRAS HEADWATERS, S. de R.L
        ///TRITUASFALTOS, S.A. de C.V.
        ///Otros- no auditoria.
        /// </summary>
        internal static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fondo_azul_oscuro {
            get {
                object obj = ResourceManager.GetObject("fondo_azul_oscuro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iniciar_sesion {
            get {
                object obj = ResourceManager.GetObject("iniciar_sesion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mas {
            get {
                object obj = ResourceManager.GetObject("mas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap portafolio {
            get {
                object obj = ResourceManager.GetObject("portafolio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon usuario {
            get {
                object obj = ResourceManager.GetObject("usuario", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
